version: '3.8'

services:
  redis:
    container_name: Redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  mysql:
    container_name: MySQL
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: your_database_name
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
